name: Build and Push to Production

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Blue or Green namespace"
        required: true
        default: "green"

  push:
    branches:
      - p

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - p

env:
  REGION: "us-east1-a"
  CLUSTER: "simple-app-p"
  NAMESPACE: ${{ github.event.inputs.namespace }}
  TAG: "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push simple-webapp image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-webapp:${{ env.TAG }}-${{ env.NAMESPACE}}-${{ github.sha }}
