name: Build, Push and Deploy to Production

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Blue or Green namespace"
        required: true
        default: "green"

  push:
    branches:
      - p

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - p

env:
  REGION: "us-east1"
  CLUSTER: "simple-app-p"
  NAMESPACE: ${{ github.event.inputs.namespace }}
  TAG: "prod"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push simple-webapp image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-webapp:${{ env.TAG }}-${{ env.NAMESPACE}}-${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER }} --zone ${{ env.REGION }}
          kubectl apply -f deployment.yml --namespace ${{ env.NAMESPACE }}
          kubectl set image deployment/simple-webapp simple-webapp=${{ secrets.DOCKERHUB_USERNAME }}/simple-webapp:${{ env.TAG }}-${{ env.NAMESPACE}}-${{ github.sha }} --namespace $NAMESPACE
