name: Build and Push to Staging

on:
  workflow_dispatch:
  push:
    branches:
      - ta

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ta

env:
  REGION: "us-east1-a"
  CLUSTER: "simple-app-ta"
  NAMESPACE: "simple-app-ta"
  TAG: "staging-${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push scooters_db image
        uses: docker/build-push-action@v5
        with:
          context: ./scooters_db
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scooters_db:${{ env.TAG }}
